version: 2
jobs:
  build:
    machine: true
    environment:
      LINUX_VERSION: UBUNTU_TRUSTY

      IMAGE_NAME: grf
      IMAGE_TAG: 3

    steps:
      - checkout

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10

      - store_artifacts:
          path: Dockerfile
